// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-m08RiKWFpQwpi2-3GbUx7PVBXJcgj8',
    appId: '1:6797267439:web:9b4df1c3ea00a6783e261a',
    messagingSenderId: '6797267439',
    projectId: 'offline-first-notes-keeper',
    authDomain: 'offline-first-notes-keeper.firebaseapp.com',
    storageBucket: 'offline-first-notes-keeper.firebasestorage.app',
    measurementId: 'G-WLHHM108GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAAkyv2Gq7Einck21w_o4orKgg1WiqM4',
    appId: '1:6797267439:android:dc3b28213e8286e93e261a',
    messagingSenderId: '6797267439',
    projectId: 'offline-first-notes-keeper',
    storageBucket: 'offline-first-notes-keeper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLN47J9O59ZVVNjiYhW_J-f1NmsSvzoDo',
    appId: '1:6797267439:ios:af71a939c64d82893e261a',
    messagingSenderId: '6797267439',
    projectId: 'offline-first-notes-keeper',
    storageBucket: 'offline-first-notes-keeper.firebasestorage.app',
    iosBundleId: 'com.example.kaykoChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLN47J9O59ZVVNjiYhW_J-f1NmsSvzoDo',
    appId: '1:6797267439:ios:af71a939c64d82893e261a',
    messagingSenderId: '6797267439',
    projectId: 'offline-first-notes-keeper',
    storageBucket: 'offline-first-notes-keeper.firebasestorage.app',
    iosBundleId: 'com.example.kaykoChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv-m08RiKWFpQwpi2-3GbUx7PVBXJcgj8',
    appId: '1:6797267439:web:b8cde69312457a893e261a',
    messagingSenderId: '6797267439',
    projectId: 'offline-first-notes-keeper',
    authDomain: 'offline-first-notes-keeper.firebaseapp.com',
    storageBucket: 'offline-first-notes-keeper.firebasestorage.app',
    measurementId: 'G-PHM03SP49C',
  );
}
